# Generated by Django 5.0.7 on 2024-08-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(related_name='products', to='products.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.city'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
