# Generated by Django 5.0.7 on 2024-08-03 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_photo_product_product_photos_alter_photo_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product'),
            preserve_default=False,
        ),
    ]
